### Test Sign Up
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Ts_12345678"
}


### Test Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "testpassword"
}


### Create profile
POST http://localhost:3000/api/dumdb/vueapp/profile
Content-Type: application/json

{
  "action": "create",
  "data": {
    "email": "kasiri.javad@gmail.com",
    "username": "123456789",
    "name": "javad kasiri",
    "phone": "+989123456789",
    "role": "admin",
    "address": {
      "country": "United Arab Emirates",
      "city": "Dubai",
      "addressLine": "42 Green Street",
      "buildingName": "Al Noor Tower",
      "no": "12B"
    }
  }
}


### Get profile
POST http://localhost:3000/api/dumdb/vueapp/profile
Content-Type: application/json

{
  "action": "get",
  "filter": {
    "username": "123456789"
  }
}

### Create custumer chat message
POST http://localhost:3000/api/dumdb/vueapp/chats
Content-Type: application/json

{
  "action": "create",
  "data": {
    "conversationId": "conv_026",
    "senderId": "customer_009",
    "receiverId": "user_009",
    "sender": "Emma Stone",
    "text": "Perfect. I’ll visit tomorrow morning.",
    "time": "3:43 PM",
      "side": "left"
  }
}

### Create user chat message
POST http://localhost:3000/api/dumdb/vueapp/chats
Content-Type: application/json

{
  "action": "create",
  "data": {
    "conversationId": "conv_026",
    "senderId": "user_009",
    "receiverId": "customer_009",
    "sender": "Michael",
    "text": "We’ll be ready to assist. Thanks for checking in!",
    "time": "3:44 PM",
    "side": "right"
  }
}

### Get chat messages
POST http://localhost:3000/api/dumdb/vueapp/chats
Content-Type: application/json

{
  "action": "get",
  "filter": {}
}

### Create a label
POST http://localhost:3000/api/dumdb/vueapp/labels
Content-Type: application/json

{
  "action": "create",
  "data": {
    "customerId": "customer_009",
    "title": "Reward points not credited",
    "description": "User claims reward points were missing after purchase.",
    "status": "Resolved",
    "createdBy": "Customer Support",
    "createdAt": "2025-07-23T12:30:00Z",
    "reviewedBy": "user",
    "reviewedAt": "2025-07-23T13:00:00Z",
    "note": "Awaiting loyalty service team response.",
    "labelImages": ["004.jpg","006.jpg","007.jpg"],
    "noteImages": ["003.jpg","005.jpg","008.jpg"],
    "labelFiles": ["001.pdf","002.pdf"],
    "noteFiles": ["003.pdf"]
  }
}

### Get labels
POST http://localhost:3000/api/dumdb/vueapp/labels
Content-Type: application/json

{
  "action": "get",
  "filter": {}
}

